handle:
  - rewrite: if(!is_dir() && !is_file() && path~"^(.*)$") goto "index.php/$1"

name: ServerState
version: 1
cron:
- description: ServerState
  url: /Pcp/ServerState
  schedule: ""*/1 * * * *""